model:
    multiscale:
        multiscale_input_channel: 3
        multiscale_output_channel: 1
    cross_attention:
        att_type: "sim_att"
    seq2vec:
        arch: skipthoughts
        dir_st: ./data
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    embed:
        embed_dim: 512
    name: AMFMN
dataset:
    datatype: rsicd
    data_split:
    data_path: './data/rsicd_precomp/'
    image_path: './data/rsicd_images/'
    vocab_path: 'vocab/rsicd_splits_vocab.json'
    batch_size: 200
    batch_size_val: 200
    workers: 4
optim:
    epochs: 50
    lr: 0.0001
    lr_decay_param: 0.7
    lr_update_epoch: 200
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
logs:
    eval_step: 1
    print_freq: 100
    ckpt_save_path: "checkpoint/"
    logger_name: 'logs/'
k_fold:
    experiment_name: 'rsicd_aba_hebing_fliter'
    nums: 5
    current_num: 0
