model:
    multiscale:
        multiscale_input_channel: 3
        multiscale_output_channel: 1
    cross_attention:
        att_type: "sim_att"
    seq2vec:
        arch: skipthoughts
        dir_st: ./data
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    embed:
        embed_dim: 512
    name: AMFMN
dataset:
    datatype: sydney
    data_split:
    data_path: './data/sydney_precomp/'
    image_path: './data/sydney_images/'
    vocab_path: 'vocab/sydney_splits_vocab.json'
    batch_size: 128
    batch_size_val: 100
    workers: 3
optim:
    epochs: 70
    lr: 0.0002
    lr_decay_param: 0.7
    lr_update_epoch: 20
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
logs:
    eval_step: 1
    print_freq: 100
    ckpt_save_path: "checkpoint/"
    logger_name: 'logs/'
k_fold:
    experiment_name: 'sydney_aba_mv_add_lose1_loss2'
    nums: 5
    current_num: 0
